on: push
jobs:
  run_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
      - run: |   
          make
          ./mis datasets/100/graph_100_1000.txt
